ci: add verification for prod.tfvars file in infrastructure provisioning workflow

diff --git a/.github/workflows/infrastructure-provisioning.yml b/.github/workflows/infrastructure-provisioning.yml
--- a/.github/workflows/infrastructure-provisioning.yml
+++ b/.github/workflows/infrastructure-provisioning.yml
@@ -121,7 +121,17 @@ jobs:
           aws_access_role    = "${{ secrets.AWS_Access_ROLE_ARN }}"
           EOF
 
-      - name: Configure AWS credentials
+      - name: Verify `prod.tfvars` File
+        run: |
+          if [ ! -f "./terraform/environments/${{ inputs.TF_ENVIRONMENT }}/prod.tfvars" ]; then
+            echo "Error: prod.tfvars file is missing!"
+            exit 1
+          else
+            echo "prod.tfvars file exists:"
+            cat ./terraform/environments/${{ inputs.TF_ENVIRONMENT }}/prod.tfvars
+          fi
+
+      - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v3
         with:
           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub-Actions
@@ -135,12 +145,6 @@ jobs:
             -backend-config="bucket=${{ secrets.TF_STATE_S3_BUCKET }}" \
             -backend-config="key=${{ inputs.TF_ENVIRONMENT }}/${{ secrets.TF_STATE_FILE_KEY }}" \
             -backend-config="dynamodb_table=${{ secrets.TF_STATE_DYNAMODB_TABLE }}"
-
-      - name: Terraform Format Check
-        if: ${{ github.event_name == 'pull_request' }}
-        run: |
-          cd infrastructure-provisioning
-          terraform fmt -check
 
       - name: Terraform Plan
         if: ${{ github.event_name == 'pull_request' }}
